# About Numpy
 
- 파이썬은 원래 계산에 특화된 언어가 아니다. 하지만 과학계산 라이브러리 NumPy를 통해 데이터과학, 수치해석, 머신러닝 등 다양한 분야에 적용이 가능해 졌다.

# NumPy 객체의 주요 속성(attribute) np.array(=np.ndarray)


- ndarray.shape : 객체의 행, 열 정보를 반환(m행, n열)
- ndarray.size : 객체의 크기(# of elements)를 반환(m n)
- ndarray.dtype : 객체의 data type을 반환
- ndarray.ndim : 객체(배열)의 차원을 반환

# NumPy 활용 (np.array)

#### 객체 생성


In [1]:
import numpy as np
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [2]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.arange(0,9) # (start,stop)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.random.uniform(0,1,10)

array([0.56350815, 0.38534099, 0.37437596, 0.22603559, 0.9628967 ,
       0.05272998, 0.60229468, 0.5745722 , 0.36283495, 0.12918589])

In [5]:
np.random.normal(0,1,10)

array([ 1.12625442, -0.92145712,  0.40453059, -0.91944218,  0.87889413,
        1.43814992, -0.60298498,  1.09671118,  0.17072376, -2.360726  ])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
Z = np.arange(1, 46).reshape(5, 9)
Z

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [8]:
np_vector = np.arange(1,13, dtype = np.int)

In [9]:
np_vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
np_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]], dtype = np.int)
np_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
np_matrix[[1, 2, 1], [0, 2, 3]] # (1,0), (2, 2), (1, 3) 선택

array([ 5, 11,  8])

# 2-dim array

In [12]:
import numpy as np
# 행렬은 열단위 작성
np_matrix_1 = np.array([[1,2,3,4],
                        [5,6,7,8],
                       [9,10,11,12]],dtype=np.int)
np_matrix_1

np_matrix_2 = np.arange(13,25,dtype=np.int).reshape(3,4)

In [13]:
np_matrix_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
np_matrix_2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [15]:
np_matrix_1+np_matrix_2

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [16]:
np_matrix_1-np_matrix_2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [17]:
np_matrix_1/np_matrix_2

array([[0.07692308, 0.14285714, 0.2       , 0.25      ],
       [0.29411765, 0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087, 0.5       ]])

In [18]:
np_matrix_1*np_matrix_2

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [19]:
np.dot(np_matrix_1,np_matrix_2.T)

# np.transpose(np_matrix_2)와 같은 기능(전치)

array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])

In [20]:
#np.dot과 같은 아웃풋 출력
np_matrix_1@np_matrix_2.T

array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])

In [21]:
# axis=0 지정시 row로
np.concatenate((np_matrix_1,np_matrix_2),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [22]:
# axis=1 지정시 col로
np.concatenate((np_matrix_1,np_matrix_2),axis=1)

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

# Broadcasting

- 원칙적으로 shape이 다른 array간의 연산은 불가능하나, broadcasting을 통해 자동으로 형태를 맞춰 연산 가능

# 그 외 자주 사용하는 NumPy 함수들

In [23]:
np_matrix_1 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]], dtype = np.int) # 3 X 4

np_vector_3 = np.array([1, 2, 3, 4], dtype = np.int)

#### np.where

In [24]:
np_vector_3 = np.array([1, 2, 3, 4], dtype = np.int)
np_vector_3

array([1, 2, 3, 4])

In [25]:
np.where(np_vector_3 > 2) # 2가 넘는 index

(array([2, 3], dtype=int64),)

In [26]:
np.where(np_vector_3 > 2, 10, 0) # 2가 넘으면, 10(True), 아니면 0(False)

array([ 0,  0, 10, 10])

In [27]:
np.where(np_matrix_1 > 6, 10, 0)

array([[ 0,  0,  0,  0],
       [ 0,  0, 10, 10],
       [10, 10, 10, 10]])

#### np.argmax/min

- max, min값이 되는 arg찾기

In [28]:
np_matrix_1 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]], dtype = np.int) # 3 X 4

np_vector_3 = np.array([1, 2, 3, 4], dtype = np.int)

In [29]:
np.argmax(np_vector_3)

3

In [30]:
np.argmax(np_matrix_1)

11

# 예외값 처리
**목표** : 예외값의 정의 및 분류에 대해 이해하고 이를 처리할 수 있도록 함.

In [31]:
np.nan

nan

In [32]:
1-np.inf

-inf

In [33]:
np.inf/np.inf

nan

In [35]:
np.exp(709)

8.218407461554972e+307

In [36]:
# 자연상수 710부터는 무한으로 표시
np.exp(710)

inf

In [37]:
# 지수함수 0에 수렴함을 의미
np.exp(-np.inf)

0.0